from emprega.tests.candidato import *
from emprega.tests.candidatura import *
from emprega.tests.curso_especializacao import *
from emprega.tests.empregador import *
from emprega.tests.empresa import *
from emprega.tests.endereco import *
from emprega.tests.experiencia_profissional import *
from emprega.tests.formacao_academica import *
from emprega.tests.idioma import *
from emprega.tests.user import *
from emprega.tests.vaga import *
