# Generated by Django 4.1.4 on 2022-12-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('emprega.user',),
        ),
        migrations.CreateModel(
            name='Empresario',
            fields=[
            ],
            options={
                'verbose_name': 'Empresário',
                'verbose_name_plural': 'Empresários',
                'ordering': ['nome'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('emprega.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='nivel_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Super Admin'), (2, 'Administrador'), (3, 'Empregador'), (4, 'Candidato')], default=4, verbose_name='Nível de Usuário'),
        ),
    ]
