# Generated by Django 4.1.4 on 2023-01-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="habilitado",
        ),
        migrations.RemoveField(
            model_name="vaga",
            name="habilitado",
        ),
        migrations.AddField(
            model_name="candidatura",
            name="esta_ativo",
            field=models.BooleanField(default=True, verbose_name="Está ativo"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="esta_ativo",
            field=models.BooleanField(default=True, verbose_name="esta_ativo"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="esta_verificado",
            field=models.BooleanField(default=False, verbose_name="esta_verificado"),
        ),
        # migrations.AddField(
        #     model_name="vaga",
        #     name="esta_ativo",
        #     field=models.BooleanField(default=True, verbose_name="Está ativo"),
        # ),
    ]
