# Generated by Django 4.1.4 on 2022-12-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursoespecializacao",
            name="certificado",
            field=models.FileField(
                null=True, upload_to="certificados", verbose_name="Certificado"
            ),
        ),
    ]
