# Generated by Django 4.1.4 on 2022-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetivoprofissional",
            name="jornada_trabalho",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Tempo Integral"),
                    (2, "Tempo Parcial"),
                    (3, "Tempo Flexível"),
                ],
                verbose_name="Jornada de trabalho",
            ),
        ),
    ]
