# Generated by Django 4.1.4 on 2022-12-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0002_alter_objetivoprofissional_jornada_trabalho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienciaprofissional",
            name="data_fim",
            field=models.DateField(null=True, verbose_name="Data de fim"),
        ),
        migrations.AlterField(
            model_name="experienciaprofissional",
            name="salario",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Salário"
            ),
        ),
        migrations.AlterField(
            model_name="formacaoacademica",
            name="data_conclusao",
            field=models.DateField(null=True, verbose_name="Data de conclusão"),
        ),
    ]
