# Generated by Django 4.1.4 on 2022-12-11 00:58

from django.db import migrations, models
import emprega.validators


class Migration(migrations.Migration):

    dependencies = [
        ('emprega', '0002_candidato_empresario_alter_user_nivel_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresario',
        ),
        migrations.CreateModel(
            name='Empregador',
            fields=[
            ],
            options={
                'verbose_name': 'Empregador',
                'verbose_name_plural': 'Empregadores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('emprega.user',),
        ),
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[emprega.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ramo_atividade',
            field=models.TextField(max_length=255, verbose_name='Ramo de atividade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[emprega.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
