# Generated by Django 4.1.4 on 2022-12-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0003_alter_experienciaprofissional_data_fim_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="area_atuacao",
            new_name="atuacao",
        ),
    ]
