# Generated by Django 4.1.4 on 2023-03-12 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprega', '0003_usuario_curriculo_processado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curriculo_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='vaga',
            name='vaga_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='vaga',
            name='vaga_processada',
            field=models.TextField(blank=True, null=True, verbose_name='Vaga Processada'),
        ),
    ]
