# Generated by Django 4.1.4 on 2022-12-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0003_avaliacao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("vaga", "usuario")},
        ),
        migrations.AlterUniqueTogether(
            name="candidatura",
            unique_together={("vaga", "usuario")},
        ),
    ]
