# Generated by Django 4.1.4 on 2023-04-08 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprega', '0004_usuario_curriculo_embedding_vaga_vaga_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoespecializacao',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='experienciaprofissional',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='formacaoacademica',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='objetivoprofissional',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('email_confirmation', 'Confirmação de Email'), ('password_reset', 'Redefinição de Senha')], max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
