# Generated by Django 4.1.4 on 2022-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0004_rename_area_atuacao_usuario_atuacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
            ],
        ),
        migrations.RemoveField(
            model_name="vaga",
            name="beneficios",
        ),
        migrations.AddField(
            model_name="vaga",
            name="beneficios",
            field=models.ManyToManyField(
                related_name="vaga_beneficios", to="emprega.beneficio"
            ),
        ),
    ]
