# Generated by Django 4.1.4 on 2022-12-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0005_beneficio_remove_vaga_beneficios_vaga_beneficios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="idade_maxima",
            field=models.PositiveIntegerField(default=65, verbose_name="Idade máxima"),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="idade_minima",
            field=models.PositiveIntegerField(default=18, verbose_name="Idade mínima"),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="quantidade_vagas",
            field=models.IntegerField(default=1, verbose_name="Quantidade de vagas"),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="sexo",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Feminino"),
                    (2, "Masculino"),
                    (3, "Não Informado"),
                    (4, "Ambos"),
                ],
                verbose_name="Sexo",
            ),
        ),
    ]
