# Generated by Django 4.1.4 on 2023-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprega', '0005_alter_cursoespecializacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="esta_ativo",
            field=models.BooleanField(default=True, verbose_name="Está ativo"),
        ),
    ]