# Generated by Django 4.1.4 on 2022-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emprega", "0006_alter_vaga_idade_maxima_alter_vaga_idade_minima_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="jornada_trabalho",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Tempo Integral"),
                    (2, "Tempo Parcial"),
                    (3, "Tempo Flexível"),
                ],
                verbose_name="Jornada de trabalho",
            ),
        ),
    ]
